---
development: &defaults
  adapter: mysql
  username: root
  password: password
  database: sinkr_development

test:
  <<: *defaults
  database: sinkr_test

production:
  <<: *defaults
  database: sinkr_production
  
rake:
  <<: *defaults